//
//  InteropEmpty.swift
//
// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the OpenTimelineIO project

import OpenTime_CXX // this works!
import OpenTimelineIO_CXX // xxx: error, comment this out for a successful build.

// this file is to demonstrate problems
// when utilizing swift/c++ interop, particularly in the import
// of Imath from the OpenTimelineIO_CXX, from the autogenerated
// umbrella header, attempting to include all Imath headers in
// the otio_header_root target.

/*
error: emit-module command failed with exit code 1 (use -v to see invocation)
/Users/furby/Wabi/OTIO/OpenTimelineIO/src/opentimelineio/serializableObject.h:15:10: note: while building module 'otio_header_root'
imported from /Users/furby/Wabi/OTIO/OpenTimelineIO/src/opentimelineio/serializableObject.h:15:
 13 | #include "opentimelineio/version.h"
 14 |
 15 | #include "ImathBox.h"
    |          `- note: while building module 'otio_header_root'
    |          imported from /Users/furby/Wabi/OTIO/OpenTimelineIO/src/opentimelineio/serializableObject.h:15:
 16 | #include "serialization.h"
 17 |

<module-includes>:12:9: note: in file included from <module-includes>:12:
 10 | #import "/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathFrustumTest.h"
 11 | #import "/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathFun.h"
 12 | #import "/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathGL.h"
    |         `- note: in file included from <module-includes>:12:
 13 | #import "/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathGLU.h"
 14 | #import "/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathInt64.h"

/Users/furby/Wabi/OTIO/OpenTimelineIO/src/deps/Imath/src/Imath/ImathGL.h:13:10: error: 'GL/gl.h' file not found
*/
